### ISSUE TITLE
几个有关使用cache的疑问

### ISSUE THREAD

**Issue by jonnywang** [jfaster/mango#1]
不错的项目，看文档中有几个疑问，请教下

```
//包省略

@DB
@Cache(prefix = "user", expire = Hour.class, num = 2)
public interface SingleKeySingeValueDao {

    @CacheIgnored
    @SQL("insert into user(uid, name) values(:1, :2)")
    public int insert(int uid, String name);

    @SQL("delete from user where uid=:1")
    public int delete(@CacheBy int uid);

    @SQL("update user set name=:2 where uid=:1")
    public int update(@CacheBy int uid, String name);

    @SQL("select uid, name from user where uid=:1")
    public User getUser(@CacheBy int uid);

}
```

1)上面delete,update,getUser时触发SimpleCacheHandler的delete,update,get是由内部sql判定吗，比如sql的select的操作触发SimpleCacheHandler的get,sql的delete对应SimpleCacheHandler的delete,sql的update对应SimpleCacheHandler的set?
2) SimpleCacheHandler的set的参数value是有Dao的方法返回值吗？ 比如

```
@SQL("select uid, name from user where uid=:1")
    public User getUser(@CacheBy int uid); //触发SimpleCacheHandler的set操作， 参数value其实就是User ?
```

3） @Cache(prefix = "user"）  prefix指定了被缓存的key前缀， 如果我想表一条记录中2个字段分别想缓存到不同的key该如何配置注解？

**Comment by liangyanghe** [comment]
1）
的确是由SQL判断的，通过select，delete，update，insert等判断请求类型，触发不同的缓存操作

2）
是的

3）
public User getUser(@CacheBy int uid, @CacheBy String name)这样是可以的，
这时key=prefix + “\_" + uid + "\_" + name

**Comment by jonnywang** [comment]
关注第三点
如果用户需求的是通过getUser读取一条记录时想保存缓存到不同的key,比如分别以uid, username保存到2个key   key1:uid  key2:username   
这样的情况改注入和注解，还是目前不支持

**Comment by liangyanghe** [comment]
这个不支持，可以考虑自己写代码完成。
不过通过Mango框架集成缓存，应该能满足70%的缓存需求～

**Comment by jonnywang** [comment]
感谢

**Comment by tongkun** [comment]
是否可以在dao内不删除db，只删除缓存？
