### ISSUE TITLE
意见：1集成spring事务管理 and  2.sql文本文件

### ISSUE THREAD

**Issue by taoyangxu** [jfaster/mango#13]
你好，十分感谢能开源出这么优秀且简洁的框架。在使用过程中，我有两个想法
1.集成spring 事务管理，这个其他同学也提到了，自己写aop的确不难。但是如果加到这个项目中，使用人员也不用去重复实现了。
2.就是把sql直接注解在dao的接口方法上，这个很直观，但是有个弊端就是sql比较长或者有sql拼接的话，写在java文件里不是很美观。我想可不可以参考一下mybatis的做法，把接口和sql分开。（当然也可以同时保留注解和sql文件，而注解的优先级高）。这个我也打算自己实现一下，到时候你们看看能不能合并呀：)
再次感谢你们~

**Comment by liangyanghe** [comment]
你好，感谢支持与鼓励，下面分别回答这两个问题
1.事务的aop支持将在1.4.1版本实现，预计在8月份release
2.mango的设计理念与目标使用群体其实就是高并发的互联网项目，一般来说用于高并发的sql都不会太复杂，所以我们在设计初期并没有考虑引入xml。不过随着框架的演进，在不影响性能的前提下，引入xml也是可以的，不过我们最好事先讨论一下实现方式，同步一下我们的设计思想。
