### ISSUE TITLE
mango和mybatis可以混合使用吗？会影响事务吗

### ISSUE THREAD

**Issue by freedomlee87** [jfaster/mango#14]

**Comment by liangyanghe** [comment]
可以混合使用，但事务是隔离开的

**Comment by freedomlee87** [comment]
mango的事务必须Transaction tx = TransactionFactory.newTransaction();代码级别控制吗,如果用spring AOP的话不可以？还是要自己写个切面，手动控制？不能像其他ORM一样托管给spring？

**Comment by liangyanghe** [comment]
不能，因为Mango考虑了分库的情况，对数据源的使用比传统ORM框架复杂，后续版本Mango会实现自己AOP的，事务AOP已经在开发中啦

**Comment by freedomlee87** [comment]
那我是不是可以实现一个aop在切面方法的执行前后使用Transaction tx = TransactionFactory.newTransaction(); 这样的操作就可以？

**Comment by liangyanghe** [comment]
可以的，建议使用TransactionTemplate使用事务，wiki如下：
http://mango.jfaster.org/transaction.html
