### ISSUE TITLE
SQL参数化建议使用名字

### ISSUE THREAD

**Issue by sjqzhang** [jfaster/mango#16]
给一个建议   @SQL("insert into fruit(name, num) values(:1, :2)") 能不能写成 @SQL("insert into fruit(name, num) values({name},{num})") 或  @SQL("insert into fruit(name, num) values($name,$num)")

**Comment by lygao** [comment]
或者写成 … values（？，？）

**Comment by liangyanghe** [comment]
java8才支持从接口中取参数名字，之前都是不支持的
