### ISSUE TITLE
关于if语句的使用

### ISSUE THREAD

**Issue by freedomlee87** [jfaster/mango#18]
if判断null是#if(:1 != null) 还是#if(:1)
还有#if(:1!= null) {} 后面是可以使用花括号的吗，这块文档太少了

**Comment by liangyanghe** [comment]
#if(:1 != null)，如果参数1不为null，最终if判断为true
#if(:1)，如果参数不为null，最终if判断为true

动态SQL的文档我找时间再细化一下，感谢提醒
