### ISSUE TITLE
表结构的sql在哪里？

### ISSUE THREAD

**Issue by xianlaioy** [jfaster/mango#2]
请问mango-example,mango test的表结构在哪？

**Comment by liangyanghe** [comment]
在 http://mango.jfaster.org 文档的各个章节中有表结构，我倒出一份在源码中吧，感谢提醒～

**Comment by liangyanghe** [comment]
在 http://mango.jfaster.org 文档的各个章节中有表结构，我倒出一份在源码中吧，感谢提醒～

**Comment by ziscloud** [comment]
@liangyanghe 没有看到文档中所用到的表结构的sql啊

**Comment by liangyanghe** [comment]
hi，请问是哪个包下的sql，我确认一下

**Comment by ziscloud** [comment]
mango-example的sql，我只能在文档上找到user的和fruit的，其他的sql都找不到，是我找错地方了吗？另外建议创建一个qq群吧，这样也好及时交流

**Comment by liangyanghe** [comment]
明天我过一遍mango-example的代码，补齐一些SQL。话说建个群确实有利于交流，哈哈

**Comment by liangyanghe** [comment]
hi，我在mango-example的每个字包下添加了README.md文件，里面包含SQL，请查看

**Comment by jonnywang** [comment]
支持群

**Comment by liangyanghe** [comment]
新建的群：445124187，欢迎加入
