### ISSUE TITLE
如何使用like？

### ISSUE THREAD

**Issue by uninxc** [jfaster/mango#28]
"#if(:1 != '' && :1 != null ) AND group_name  like '%#{:1}%'  #end "

该框架不认为在单引号里面的是一个变量 #{:1}

**Comment by liangyanghe** [comment]
group_name like :1
其中:1里是字符串“%xxxx”
这样就行

**Comment by uninxc** [comment]
如果是需要“%xxxx%” 呢？

**Comment by uninxc** [comment]
@liangyanghe  你说的 [group_name like :1 ]这种 不生效，只是完全匹配模式，而不是加了通配符

**Comment by uninxc** [comment]
OK！ 3ks！
