### ISSUE TITLE
调用错误

### ISSUE THREAD

**Issue by 137268431** [jfaster/mango#36]
addAndReturnGeneratedId 调用出现
![image](https://user-images.githubusercontent.com/5044713/43389814-38e084ec-941f-11e8-99bf-a245f0291198.png)
![image](https://user-images.githubusercontent.com/5044713/43389842-4c20d23c-941f-11e8-9d7e-c2d3ead4d6b5.png)
错误

**Comment by liangyanghe** [comment]
需要数据设置自增ID
