### ISSUE TITLE
主库从库配置中多个库的情况如何配置

### ISSUE THREAD

**Issue by jenopob** [jfaster/mango#39]
`
    <bean id="masterSlaveDataSourceFactory" class="org.jfaster.mango.datasource.MasterSlaveDataSourceFactory">
        <property name="name" value="dsf2" />
        <property name="master">
            <bean class="org.jfaster.mango.datasource.DriverManagerDataSource">
                <property name="driverClassName" value="com.mysql.jdbc.Driver" />
                <property name="url" value="jdbc:mysql://localhost:3306/mango_example_master" />
                <property name="username" value="root" />
                <property name="password" value="root" />
            </bean>
        </property>
        <property name="slaves">
            <list>
                <bean class="org.jfaster.mango.datasource.DriverManagerDataSource">
                    <property name="driverClassName" value="com.mysql.jdbc.Driver" />
                    <property name="url" value="jdbc:mysql://localhost:3306/mango_example_slave1" />
                    <property name="username" value="root" />
                    <property name="password" value="root" />
                </bean>
                <bean class="org.jfaster.mango.datasource.DriverManagerDataSource">
                    <property name="driverClassName" value="com.mysql.jdbc.Driver" />
                    <property name="url" value="jdbc:mysql://localhost:3306/mango_example_slave2" />
                    <property name="username" value="root" />
                    <property name="password" value="root" />
                </bean>
            </list>
        </property>
    </bean>`

是在master节点里面增加多个org.jfaster.mango.datasource.DriverManagerDataSource吗？

比如我主库有base, trade,td0,td1,td2,td3,td4...N个，slave库也有同样的那么多。该如何配置

**Comment by liangyanghe** [comment]
请查看：http://mango.jfaster.org/datasource.html

**Comment by jenopob** [comment]
OK,这个项目怎么不维护下去了？
