### ISSUE TITLE
框架集成后针对部分引用会出现找不到的情况

### ISSUE THREAD

**Issue by zhangxiao918** [jfaster/mango#4]
最近在了解Mongo，从Github导入到IntellJ后发现有类找不到的情况，例如：
org.jfaster.mango.parser.AbstractExpression 找不到父类SimpleNode，同时也找不到Parse，基本上【org.jfaster.mango.parser】 包下的类都是报错的，这块的依赖库定义没有体现在pom.xml中，能否明确一下这块的引用吗？ 谢谢了！

**Comment by liangyanghe** [comment]
你好，Mango框架使用了javacc进行词法分析和语法分析，这部分代码是由javacc生成的。一般情况下在导入代码的过程中这部分代码会由maven自动生成，请提供一下maven和IntelLJ版本号

**Comment by liangyanghe** [comment]
hi，为解决有些maven版本和javacc插件冲突的问题，我已经将javacc生成的代码拷贝到了org.jfaster.mango.parser包下，请更新到最新代码，再用IDE导入

**Comment by zhangxiao918** [comment]
hi,liangyanghe,更新代码后，问题解决了！ 谢谢！
