### ISSUE TITLE
DAO在springboot中Autowired问题

### ISSUE THREAD

**Issue by jenopob** [jfaster/mango#41]
使用
`<dependency>
            <groupId>org.jfaster</groupId>
            <artifactId>mango-spring-boot-starter</artifactId>
            <version>0.4</version>
        </dependency>`

有一句WARN日志

`WARN  [o.s.context.annotation.ConfigurationClassEnhancer] - @Bean method MangoAutoConfiguration.autoCreator is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.`

然后导致boot中定义的service类中@Autowired持久层DAO就无法识别到了

**Comment by jenopob** [comment]
`01-03 16:19:26.131 WARN  [o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'multiAddrAnalyzeController': Unsatisfied dependency expressed through field 'regionService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'regionService': Unsatisfied dependency expressed through field 'regionDao'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.gamma.address.dao.RegionDao' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`

**Comment by SuperIllidan** [comment]
> 
> 
> 使用
> `<dependency> <groupId>org.jfaster</groupId> <artifactId>mango-spring-boot-starter</artifactId> <version>0.4</version> </dependency>`
> 
> 有一句WARN日志
> 
> `WARN [o.s.context.annotation.ConfigurationClassEnhancer] - @Bean method MangoAutoConfiguration.autoCreator is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.`
> 
> 然后导致boot中定义的service类中@Autowired持久层DAO就无法识别到了

As you are using this starter, if u refer the source code,  u'll find that it would only register those classes with class name ending with "Dao" and "DAO".

**Comment by jenopob** [comment]
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
            <scope>true</scope>
        </dependency>

在idea里面要把这个依赖去了，才可以。

**Comment by jenopob** [comment]
` <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
            <scope>true</scope>
        </dependency>`

在idea把这个依赖去了才可以
