### ISSUE TITLE
SQL中连接几个分表查询，框架有实现吗

### ISSUE THREAD

**Issue by oawang** [jfaster/mango#7]
如 select * form order o left join sub_order s on o.order_id=s.order_id

此时 order和sub_order都是根据某一规则进行分库分表

**Comment by liangyanghe** [comment]
hi，这个是不支持的

**Comment by oawang** [comment]
还有解决方案吗。。我有看到你的提供的Interceptor接口，，参否能这接口里面加个方法上下文

**Comment by liangyanghe** [comment]
请考虑下面的问题：
order表在db1
sub_order表在db2
他们是不可以进行join查询的

**Comment by oawang** [comment]
嗯。。你说的这个肯定是不可以，但也有这样的规则，就是每个用户一生成的时候，同时也生成对应的分库分表下标，例如分表下标分别是1，则order和sub_order是在同一库上，分表都是1

**Comment by oawang** [comment]
设计上已经把order 和 sub_order指定在同一库上，至于在哪个库，是由生成用户的时候一并生成出来的，此时就已经知道该用户是哪个库哪个表下标

**Comment by oawang** [comment]
还有个问题就是，能否参考一下spring的扩展性，XxxFactory一般都是可以让开发人员设置进来的，没有设置才会使用默认XxxFactory

**Comment by liangyanghe** [comment]
最好的办法就是分两次读出表数据，然后在应用服务器中进行内存中计算，高并发的服务理应是杜绝join语句的。

**Comment by liangyanghe** [comment]
请问一下XxxFactory是什么？

**Comment by oawang** [comment]
高并发的服务理应是杜绝join语句的???求大师分析，这个还不太明白

**Comment by oawang** [comment]
哦，参考shiro框架，扩展性很好

**Comment by liangyanghe** [comment]
join会过多的占用数据库的cpu和内存资源

**Comment by oawang** [comment]
不Join的话。就会多执行几次sql，这样不会更容易造成数据的问题吗

**Comment by liangyanghe** [comment]
还是有区别的，具体可以询问一下你们公司的DBA

**Comment by oawang** [comment]
好的，你能开源一下词法jj文件吗

**Comment by liangyanghe** [comment]
请看这里 https://github.com/jfaster/mango/blob/master/src/main/jjtree/parser.jjt
