### ISSUE TITLE
同一SQL查询所有oracle数据库分表

### ISSUE THREAD

**Issue by Lockie921** [jfaster/mango#8]
之前循环将分库下标当做一个变量传进来查询发现会有ORA-00933这种错误出现，不过这种办法在mysql中就没有任何问题。新手求大神解惑，万分感谢。

**Comment by liangyanghe** [comment]
你好，我们也用oracle循环过分库，并没遇到此问题。
请贴出你的代码和异常栈信息，同时给一下ojdbc和oracle的版本。
如果觉得github贴图不方便，可以把信息发到mango@jfaster.org，我会尽快恢复。
